"use client";

import { useState, useEffect, useRef } from "react";
import Link from "next/link";

// ─── Data ─────────────────────────────────────────────────────────────────────

const CATEGORIES = [
  {
    id: "retirement",
    label: "Retirement",
    icon: "🌅",
    color: "from-amber-500/20 to-orange-500/10",
    accent: "#f59e0b",
    calcs: [
      { title: "Social Security Retirement Income Estimator", href: "https://www.ssa.gov/estimator/" },
      { title: "How Does Inflation Impact My Retirement Income Needs?", href: "#" },
      { title: "Convert Discretionary Expenses to Savings", href: "#" },
    ],
  },
  {
    id: "savings",
    label: "Savings",
    icon: "💰",
    color: "from-emerald-500/20 to-teal-500/10",
    accent: "#10b981",
    calcs: [
      { title: "Becoming a Millionaire", href: "#" },
      { title: "How Long Will It Take to Double My Money?", href: "#" },
      { title: "How Long Until My Savings Reach My Goal?", href: "#" },
      { title: "Save Now vs. Save Later", href: "#" },
      { title: "How Much Should I Save to Reach My Goal?", href: "#" },
      { title: "What Will My Current Savings Grow To?", href: "#" },
      { title: "Calculate Rate of Return", href: "#" },
      { title: "How Do Taxes and Inflation Impact My Return?", href: "#" },
    ],
  },
  {
    id: "insurance",
    label: "Insurance",
    icon: "🛡️",
    color: "from-blue-500/20 to-indigo-500/10",
    accent: "#3b82f6",
    calcs: [
      { title: "What Is My Life Expectancy?", href: "#" },
      { title: "What Are the Chances of Becoming Disabled?", href: "#" },
      { title: "How Much Will I Earn in My Lifetime?", href: "#" },
      { title: "What Are the Tax Advantages of an Annuity?", href: "#" },
      { title: "How Long Will My Current Life Insurance Proceeds Last?", href: "#" },
    ],
  },
  {
    id: "taxation",
    label: "Taxation",
    icon: "📋",
    color: "from-purple-500/20 to-violet-500/10",
    accent: "#8b5cf6",
    calcs: [
      { title: "Federal Income Tax Calculator", href: "#" },
      { title: "How Much Self-Employment Tax Will I Pay?", href: "#" },
      { title: "What Is My Tax-Equivalent Yield?", href: "#" },
      { title: "Tax Refund Estimator", href: "#" },
      { title: "Tax Freedom Day", href: "#" },
    ],
  },
  {
    id: "mortgage",
    label: "Home & Mortgage",
    icon: "🏠",
    color: "from-rose-500/20 to-pink-500/10",
    accent: "#f43f5e",
    calcs: [
      { title: "Comprehensive Mortgage Calculator", href: "#" },
      { title: "Should I Convert to a Bi-Weekly Payment Schedule?", href: "#" },
      { title: "What Are the Tax Savings Generated by My Mortgage?", href: "#" },
      { title: "Compare an Interest-Only vs. Traditional Mortgage", href: "#" },
    ],
  },
  {
    id: "college",
    label: "College",
    icon: "🎓",
    color: "from-sky-500/20 to-cyan-500/10",
    accent: "#0ea5e9",
    calcs: [
      { title: "Will I Be Able to Pay Back My Student Loans?", href: "#" },
      { title: "Advantages of the Coverdell ESA", href: "#" },
      { title: "Advantages of a 529 College Savings Plan", href: "#" },
      { title: "What Is the Value of a College Education?", href: "#" },
      { title: "What Are the Payments on a Parental (PLUS) Loan?", href: "#" },
    ],
  },
  {
    id: "cashflow",
    label: "Cash Flow",
    icon: "💸",
    color: "from-lime-500/20 to-green-500/10",
    accent: "#84cc16",
    calcs: [
      { title: "Should I Pay Down Debt or Invest More?", href: "#" },
      { title: "How Long Will My Money Last?", href: "#" },
      { title: "Historical Inflation – Compare Purchasing Power", href: "#" },
    ],
  },
  {
    id: "credit",
    label: "Credit",
    icon: "💳",
    color: "from-orange-500/20 to-red-500/10",
    accent: "#f97316",
    calcs: [
      { title: "How Long Will It Take to Pay Off My Credit Card(s)?", href: "#" },
      { title: "How Long Until My Loan Is Paid Off?", href: "#" },
      { title: "What Would My Loan Payments Be?", href: "#" },
      { title: "What Is the Balance Owing on My Loan?", href: "#" },
      { title: "Which Is Better, Cash Up Front or Payments Over Time?", href: "#" },
      { title: "What Is the Impact of Making Extra Debt Payments?", href: "#" },
      { title: "Should I Pay Off Debts or Invest the Money?", href: "#" },
    ],
  },
  {
    id: "paycheck",
    label: "Paycheck & Benefits",
    icon: "📊",
    color: "from-teal-500/20 to-emerald-500/10",
    accent: "#14b8a6",
    calcs: [
      { title: "Convert My Salary to an Equivalent Hourly Wage", href: "#" },
      { title: "Convert My Hourly Wage to an Equivalent Salary", href: "#" },
    ],
  },
  {
    id: "auto",
    label: "Auto",
    icon: "🚗",
    color: "from-slate-500/20 to-gray-500/10",
    accent: "#64748b",
    calcs: [
      { title: "Auto Purchase – Loan vs. 0% Dealer Financing?", href: "#" },
      { title: "What Would My Auto Payments Be?", href: "#" },
      { title: "Auto Loan – Accelerated Payoff", href: "#" },
    ],
  },
  {
    id: "finra",
    label: "FINRA Calculators",
    icon: "🏛️",
    color: "from-indigo-500/20 to-blue-500/10",
    accent: "#6366f1",
    finra: true,
    calcs: [
      { title: "Smart Bond Investing Accrued Interest Calculator", href: "https://www.finra.org/investors/tools-and-calculators/bond-accrued-interest-calculator" },
      { title: "Retirement Calculator", href: "https://tools.finra.org/retirement-calculator/" },
      { title: "College Savings Calculator", href: "https://tools.finra.org/college-savings/" },
      { title: "Savings Calculator", href: "https://tools.finra.org/savings-calculator/" },
      { title: "401(k) and IRA Minimum Required Distribution Calculator", href: "https://tools.finra.org/mrd-calculator/" },
      { title: "401(k) 'Save the Max' Calculator", href: "https://tools.finra.org/save-the-max/" },
    ],
  },
];

const ALL_CALCS = CATEGORIES.flatMap((cat) =>
  cat.calcs.map((c) => ({ ...c, category: cat.label, categoryId: cat.id }))
);

// ─── Utilities ────────────────────────────────────────────────────────────────

function useInView(threshold = 0.06) {
  const ref = useRef(null);
  const [inView, setInView] = useState(false);
  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => { if (entry.isIntersecting) setInView(true); },
      { threshold }
    );
    if (ref.current) observer.observe(ref.current);
    return () => observer.disconnect();
  }, [threshold]);
  return [ref, inView];
}

const ArrowRight = () => (
  <svg className="w-4 h-4 shrink-0" fill="none" stroke="currentColor" strokeWidth="2"
    viewBox="0 0 24 24" strokeLinecap="round" strokeLinejoin="round">
    <path d="M5 12h14M12 5l7 7-7 7" />
  </svg>
);

const ExternalLink = () => (
  <svg className="w-3 h-3 shrink-0 opacity-50" fill="none" stroke="currentColor" strokeWidth="2"
    viewBox="0 0 24 24" strokeLinecap="round" strokeLinejoin="round">
    <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6" />
    <polyline points="15 3 21 3 21 9" />
    <line x1="10" y1="14" x2="21" y2="3" />
  </svg>
);

const SearchIcon = () => (
  <svg className="w-4 h-4" fill="none" stroke="currentColor" strokeWidth="2"
    viewBox="0 0 24 24" strokeLinecap="round" strokeLinejoin="round">
    <circle cx="11" cy="11" r="8" />
    <line x1="21" y1="21" x2="16.65" y2="16.65" />
  </svg>
);

const ClearIcon = () => (
  <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" strokeWidth="2.5"
    viewBox="0 0 24 24" strokeLinecap="round" strokeLinejoin="round">
    <line x1="18" y1="6" x2="6" y2="18" />
    <line x1="6" y1="6" x2="18" y2="18" />
  </svg>
);

// ─── Section 1: Hero ──────────────────────────────────────────────────────────

function PageHero({ search, setSearch, totalCount }) {
  const [visible, setVisible] = useState(false);
  useEffect(() => { setTimeout(() => setVisible(true), 80); }, []);
  const fu = (d = "") =>
    `transition-all duration-700 ease-out ${d} ${visible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-6"}`;

  return (
    <>
      <style>{`
        .cl-hero-bg {
          background-color: var(--color-navy-deep);
          background-image:
            radial-gradient(ellipse 60% 55% at 88% 20%, color-mix(in srgb, var(--color-navy) 82%, transparent) 0%, transparent 60%),
            radial-gradient(ellipse 55% 65% at 8%  88%, color-mix(in srgb, var(--color-gold) 11%, transparent) 0%, transparent 55%);
        }
        .cl-grain::after {
          content:""; position:absolute; inset:0; pointer-events:none; opacity:0.3;
          background-image:url("data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='0.03'/%3E%3C/svg%3E");
        }
        @keyframes cl-spin { from{transform:rotate(0deg)} to{transform:rotate(360deg)} }
        .cl-ring { animation: cl-spin 65s linear infinite; }
        .search-input::placeholder { color: rgba(148,163,184,0.6); }
        .search-input:focus { outline: none; }
      `}</style>

      <section className="font-body cl-hero-bg cl-grain relative overflow-hidden py-24 lg:py-28">
        <div className="cl-ring absolute -right-44 -top-44 w-[600px] h-[600px] rounded-full border border-white/[0.04] pointer-events-none" />
        <div className="absolute -right-28 -top-28 w-[440px] h-[440px] rounded-full border border-gold/[0.05] pointer-events-none" />
        <div className="absolute bottom-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-gold/30 to-transparent" />

        <div className="relative z-10 max-w-7xl mx-auto px-6 sm:px-10 lg:px-16">
          <div className="max-w-2xl mx-auto text-center">
            <nav className={`flex items-center justify-center gap-2 mb-8 text-xs transition-all duration-500 ${visible ? "opacity-100" : "opacity-0"}`}>
              <Link href="/" className="font-body text-slate-400 hover:text-gold transition-colors">Home</Link>
              <span className="text-white/20">/</span>
              <Link href="/resources" className="font-body text-slate-400 hover:text-gold transition-colors">Resources</Link>
              <span className="text-white/20">/</span>
              <span className="font-body text-gold">Financial Calculators</span>
            </nav>

            <div className={`${fu("delay-100")} inline-flex items-center gap-3 mb-6 justify-center`}>
              <span className="w-8 h-px bg-gold" />
              <span className="font-body text-gold text-xs uppercase tracking-[0.25em] font-bold">Free Tools</span>
              <span className="w-8 h-px bg-gold" />
            </div>

            <h1 className={`${fu("delay-200")} font-heading text-white leading-[1.1] mb-5 text-[clamp(2.4rem,5vw,4rem)]`}>
              Financial<br />
              <em className="not-italic text-gold">Calculator Library.</em>
            </h1>

            <p className={`${fu("delay-300")} font-body text-slate-400 text-sm leading-relaxed mb-8 max-w-lg mx-auto`}>
              {totalCount} interactive calculators across {CATEGORIES.length} categories — built to help
              you model scenarios, estimate costs, and make more informed financial decisions.
            </p>

            {/* Search bar */}
            <div className={`${fu("delay-400")} relative max-w-md mx-auto`}>
              <div className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400 pointer-events-none">
                <SearchIcon />
              </div>
              <input
                type="text"
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                placeholder="Search calculators…"
                className="search-input w-full bg-white/8 border border-white/15 hover:border-white/25
                           focus:border-gold/50 text-white text-sm pl-10 pr-10 py-3.5 rounded-xl
                           transition-colors duration-200"
              />
              {search && (
                <button
                  onClick={() => setSearch("")}
                  className="absolute right-4 top-1/2 -translate-y-1/2 text-slate-400 hover:text-white transition-colors">
                  <ClearIcon />
                </button>
              )}
            </div>
          </div>
        </div>
      </section>
    </>
  );
}

// ─── Search Results ───────────────────────────────────────────────────────────

function SearchResults({ query, results }) {
  if (!query) return null;

  return (
    <section className="font-body bg-slate-50 py-12 border-b border-slate-200">
      <div className="max-w-7xl mx-auto px-6 sm:px-10 lg:px-16">
        <div className="flex items-center gap-3 mb-6">
          <span className="font-body text-slate-500 text-sm">
            {results.length} result{results.length !== 1 ? "s" : ""} for
          </span>
          <span className="font-heading text-navy text-sm font-bold">&ldquo;{query}&rdquo;</span>
        </div>

        {results.length === 0 ? (
          <div className="text-center py-10">
            <p className="font-heading text-navy text-lg mb-2">No calculators found.</p>
            <p className="font-body text-slate-400 text-sm">Try a different keyword, or browse by category below.</p>
          </div>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
            {results.map((calc, i) => (
              <a key={i} href={calc.href} target="_blank" rel="noopener noreferrer"
                className="group flex items-start gap-3 bg-white border border-slate-100
                           hover:border-gold/30 hover:shadow-md rounded-xl px-5 py-4
                           transition-all duration-200 hover:-translate-y-0.5">
                <div className="flex-1">
                  <div className="font-body text-[10px] uppercase tracking-wider text-slate-400 mb-1">{calc.category}</div>
                  <div className="font-heading text-navy text-sm font-bold leading-snug group-hover:text-gold transition-colors">
                    {calc.title}
                  </div>
                </div>
                <span className="text-slate-300 group-hover:text-gold mt-0.5 transition-colors"><ExternalLink /></span>
              </a>
            ))}
          </div>
        )}
      </div>
    </section>
  );
}

// ─── Category Filter Pills ────────────────────────────────────────────────────

function CategoryFilter({ activeId, setActiveId }) {
  const [ref, inView] = useInView(0.1);

  return (
    <div ref={ref}
      className={`sticky top-[80px] z-30 bg-white border-b border-slate-100 shadow-sm
                   transition-all duration-700 ease-out ${inView ? "opacity-100 translate-y-0" : "opacity-0 -translate-y-2"}`}>
      <div className="max-w-7xl mx-auto px-6 sm:px-10 lg:px-16">
        <div className="flex items-center gap-2 py-3 overflow-x-auto scrollbar-none">
          <button
            onClick={() => setActiveId(null)}
            className={`shrink-0 font-body text-xs font-bold uppercase tracking-wider px-4 py-2 rounded-full
                         transition-all duration-200 ${
              activeId === null
                ? "bg-navy text-white shadow-sm"
                : "text-slate-500 hover:text-navy hover:bg-slate-100"
            }`}>
            All
          </button>
          {CATEGORIES.map((cat) => (
            <button key={cat.id}
              onClick={() => setActiveId(activeId === cat.id ? null : cat.id)}
              className={`shrink-0 flex items-center gap-1.5 font-body text-xs font-bold uppercase tracking-wider
                           px-4 py-2 rounded-full transition-all duration-200 ${
                activeId === cat.id
                  ? "bg-navy text-white shadow-sm"
                  : "text-slate-500 hover:text-navy hover:bg-slate-100"
              }`}>
              <span className="text-sm leading-none">{cat.icon}</span>
              {cat.label}
            </button>
          ))}
        </div>
      </div>
    </div>
  );
}

// ─── Category Card ────────────────────────────────────────────────────────────

function CategoryCard({ cat, isHighlighted }) {
  const [ref, inView] = useInView(0.05);
  const [expanded, setExpanded] = useState(false);
  const PREVIEW = 4;
  const showToggle = cat.calcs.length > PREVIEW;
  const visible = expanded ? cat.calcs : cat.calcs.slice(0, PREVIEW);

  return (
    <div
      id={cat.id}
      ref={ref}
      className={`scroll-mt-32 bg-white rounded-3xl border overflow-hidden
                   transition-all duration-700 ease-out
                   ${isHighlighted ? "border-gold/40 shadow-xl ring-2 ring-gold/20" : "border-slate-100 shadow-sm"}
                   ${inView ? "opacity-100 translate-y-0" : "opacity-0 translate-y-8"}`}>

      {/* Card header */}
      <div className={`bg-gradient-to-br ${cat.color} px-7 py-6 border-b border-slate-100`}>
        <div className="flex items-center gap-4">
          <span className="text-3xl">{cat.icon}</span>
          <div className="flex-1">
            <div className="flex items-center gap-2 flex-wrap">
              <h2 className="font-heading text-navy text-xl font-bold">{cat.label}</h2>
              {cat.finra && (
                <span className="font-body text-[9px] uppercase tracking-widest text-indigo-600 bg-indigo-50 border border-indigo-100 px-2 py-0.5 rounded-full font-bold">
                  External — FINRA.org
                </span>
              )}
            </div>
            <p className="font-body text-slate-500 text-xs mt-0.5">
              {cat.calcs.length} calculator{cat.calcs.length !== 1 ? "s" : ""}
            </p>
          </div>
        </div>
      </div>

      {/* Calculator list */}
      <ul className="divide-y divide-slate-50">
        {visible.map((calc, i) => (
          <li key={i}>
            <a href={calc.href} target="_blank" rel="noopener noreferrer"
              className="group flex items-center gap-3 px-7 py-3.5
                         hover:bg-slate-50 transition-colors duration-150">
              <div className="w-1.5 h-1.5 rounded-full bg-slate-200 group-hover:bg-gold shrink-0 transition-colors" />
              <span className="font-body text-slate-700 group-hover:text-navy text-sm flex-1 leading-snug transition-colors">
                {calc.title}
              </span>
              <span className="text-slate-300 group-hover:text-gold transition-colors shrink-0"><ExternalLink /></span>
            </a>
          </li>
        ))}
      </ul>

      {/* Show more / less */}
      {showToggle && (
        <div className="px-7 py-3 border-t border-slate-50">
          <button
            onClick={() => setExpanded(!expanded)}
            className="font-body text-xs font-bold uppercase tracking-wider text-slate-400
                       hover:text-navy flex items-center gap-1.5 transition-colors duration-200">
            {expanded
              ? `Show fewer`
              : `Show ${cat.calcs.length - PREVIEW} more`}
            <svg className={`w-3.5 h-3.5 transition-transform duration-200 ${expanded ? "rotate-180" : ""}`}
              fill="none" stroke="currentColor" strokeWidth="2.5" viewBox="0 0 24 24">
              <polyline points="6 9 12 15 18 9" />
            </svg>
          </button>
        </div>
      )}
    </div>
  );
}

// ─── Disclaimer ───────────────────────────────────────────────────────────────

function Disclaimer() {
  const [ref, inView] = useInView(0.1);

  return (
    <section ref={ref}
      className={`font-body bg-slate-50 border-t border-slate-200 py-12
                   transition-all duration-700 ease-out ${inView ? "opacity-100 translate-y-0" : "opacity-0 translate-y-4"}`}>
      <div className="max-w-7xl mx-auto px-6 sm:px-10 lg:px-16">
        <div className="max-w-4xl mx-auto">
          <div className="flex items-start gap-4 mb-5">
            <div className="w-8 h-8 rounded-xl bg-amber-50 border border-amber-100 flex items-center justify-center shrink-0">
              <svg className="w-4 h-4 text-amber-500" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z" />
              </svg>
            </div>
            <div>
              <h3 className="font-heading text-navy text-sm font-bold mb-3">Link & Calculator Disclosures</h3>
              <div className="flex flex-col gap-3">
                <p className="font-body text-slate-500 text-xs leading-relaxed">
                  <span className="font-bold text-slate-600">Third-party links: </span>
                  The information provided is strictly as a courtesy. When you click on any of the links provided here,
                  you are leaving this website and viewing information provided by a third party. We make no representation
                  as to the completeness or accuracy of information provided by any third-party website. Nor is the company
                  liable for any direct or indirect technical or system issues or any consequences arising out of your access
                  to or use of third-party technologies, websites, information, and programs made available through this website.
                  By accessing these calculators, you assume total responsibility and risk for your use of the third-party website.
                </p>
                <p className="font-body text-slate-500 text-xs leading-relaxed">
                  <span className="font-bold text-slate-600">Calculator limitations: </span>
                  Information and interactive calculators are made available to you as self-help tools for your independent use
                  and are not intended to provide investment, tax, or legal advice. We cannot and do not guarantee their
                  applicability or accuracy in regard to your individual circumstances. All examples are hypothetical and are
                  for illustrative purposes. We encourage you to seek personalized advice from qualified professionals
                  regarding all personal finance issues.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

// ─── CTA ──────────────────────────────────────────────────────────────────────

function CalculatorCTA() {
  const [ref, inView] = useInView(0.15);

  return (
    <section ref={ref} className="font-body bg-white py-16 lg:py-20">
      <div className="max-w-7xl mx-auto px-6 sm:px-10 lg:px-16">
        <div className={`bg-navy rounded-3xl p-8 lg:p-12 relative overflow-hidden
                          transition-all duration-700 ease-out ${inView ? "opacity-100 translate-y-0" : "opacity-0 translate-y-8"}`}>
          <div className="absolute -right-20 -top-20 w-72 h-72 rounded-full border border-white/[0.05] pointer-events-none" />
          <div className="absolute -right-8 -top-8 w-48 h-48 rounded-full border border-gold/[0.08] pointer-events-none" />

          <div className="relative z-10 flex flex-col lg:flex-row items-start lg:items-center justify-between gap-6">
            <div className="max-w-xl">
              <p className="font-body text-gold text-xs uppercase tracking-[0.25em] font-bold mb-2">Ready for the real thing?</p>
              <h2 className="font-heading text-white text-[clamp(1.4rem,2.5vw,2rem)] leading-tight mb-2">
                Calculators show estimates.<br />
                <em className="not-italic text-gold">We build your actual plan.</em>
              </h2>
              <p className="font-body text-slate-300 text-sm leading-relaxed">
                A personalized financial plan goes far beyond any calculator. Schedule a complimentary
                consultation and let us put the numbers in context for your specific situation.
              </p>
            </div>
            <div className="flex flex-col sm:flex-row gap-3 shrink-0">
              <Link href="/contact"
                className="inline-flex items-center justify-center gap-2 px-6 py-3.5 rounded-full
                           font-heading text-navy-deep text-sm font-bold uppercase tracking-wider
                           bg-gradient-to-r from-gold to-gold-light hover:from-gold-light hover:to-gold
                           transition-all duration-300 hover:shadow-[0_8px_32px_rgba(201,168,76,0.3)]
                           hover:-translate-y-0.5">
                Book a Consultation <ArrowRight />
              </Link>
              <Link href="/services"
                className="inline-flex items-center justify-center gap-2 px-6 py-3.5 rounded-full
                           border border-white/20 hover:border-white/40 text-white
                           font-body text-sm transition-all duration-300 hover:bg-white/5">
                Our Services
              </Link>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

// ─── Page ─────────────────────────────────────────────────────────────────────

export default function CalculatorLibraryPage() {
  const [search, setSearch]     = useState("");
  const [activeId, setActiveId] = useState(null);

  const searchResults = search.trim()
    ? ALL_CALCS.filter((c) =>
        c.title.toLowerCase().includes(search.toLowerCase()) ||
        c.category.toLowerCase().includes(search.toLowerCase())
      )
    : [];

  const visibleCategories = activeId
    ? CATEGORIES.filter((c) => c.id === activeId)
    : CATEGORIES;

  // Scroll to category when pill is clicked
  useEffect(() => {
    if (activeId) {
      const el = document.getElementById(activeId);
      if (el) el.scrollIntoView({ behavior: "smooth", block: "start" });
    }
  }, [activeId]);

  const totalCount = ALL_CALCS.length;

  return (
    <>
      <PageHero search={search} setSearch={setSearch} totalCount={totalCount} />
      {search ? (
        <SearchResults query={search} results={searchResults} />
      ) : (
        <>
          <CategoryFilter activeId={activeId} setActiveId={setActiveId} />
          <main className="font-body bg-slate-50 py-16 lg:py-20">
            <div className="max-w-7xl mx-auto px-6 sm:px-10 lg:px-16">
              <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                {visibleCategories.map((cat) => (
                  <CategoryCard
                    key={cat.id}
                    cat={cat}
                    isHighlighted={activeId === cat.id}
                  />
                ))}
              </div>
            </div>
          </main>
        </>
      )}
      <Disclaimer />
      <CalculatorCTA />
    </>
  );
}